# Generated by Django 5.2.1 on 2025-05-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
